import {
  IconAlertTriangle,
  IconArrowRight,
  IconCheck,
  IconChevronLeft,
  IconChevronRight,
  IconCommand,
  IconCreditCard,
  IconFile,
  IconFileText,
  IconHelpCircle,
  IconPhoto,
  IconDeviceLaptop,
  IconLayoutDashboard,
  IconLoader2,
  IconLogin,
  IconProps,
  IconShoppingBag,
  IconMoon,
  IconDotsVertical,
  IconPizza,
  IconPlus,
  IconSettings,
  IconSun,
  IconTrash,
  IconBrandTwitter,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconX,
  IconLayoutKanban,
  IconBrandGithub,
  IconBattery,
  IconUsers,
  IconPackage,
  IconBarChart3,
  IconUserCog,
  IconList,
  IconUserPlus,
  IconShield,
  IconActivity,
  IconCog,
  IconReceipt,
  IconFilePlus,
  IconPrinter,
  IconTrendingUp,
  IconPieChart,
  IconDownload,
  IconDot
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  dashboard: IconLayoutDashboard,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,
  // E-Wheels specific icons
  battery: IconBattery,
  users: IconUsers,
  package: IconPackage,
  barChart3: IconBarChart3,
  userCog: IconUserCog,
  list: IconList,
  userPlus: IconUserPlus,
  shield: IconShield,
  activity: IconActivity,
  cog: IconCog,
  fileText: IconFileText,
  receipt: IconReceipt,
  filePlus: IconFilePlus,
  printer: IconPrinter,
  trendingUp: IconTrendingUp,
  pieChart: IconPieChart,
  download: IconDownload,
  dot: IconDot,
  alertTriangle: IconAlertTriangle,
  plus: IconPlus
};
